# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, spec, ... }:

let
  registry = import ../../network/registry.nix;
  n = spec.facts.network;
  myLan = registry.machines.${spec.hostName}.lan or {};
in {
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d482131a-5473-40bc-b89e-62ce432f4a5f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d482131a-5473-40bc-b89e-62ce432f4a5f".device = "/dev/disk/by-uuid/d482131a-5473-40bc-b89e-62ce432f4a5f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/20BC-9A7B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  networking.interfaces.${myLan.interface} = {
    useDHCP = false;
    ipv4.addresses = [
      {
        address = myLan.ip;
        prefixLength = 24;
      }
    ];
  };

  networking.defaultGateway = "192.168.8.1";
  networking.nameservers = [
    "192.168.8.1"
    "1.1.1.1"
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
